version: '3.4'

volumes:
  sequencer_geth_data:

services:
  morph-geth:
    build:
      context: .
      dockerfile: Dockerfile
    image: morphism-geth:latest
    ports:
      - "8545:8545"
      - "8546:8546"
      - "8551:8551"
      - "30303:30303"
    volumes:
      - "sequencer_geth_data:${GETH_DATA_DIR}"
      - "${PWD}/build/jwt-secret.txt:${JWT_SECRET_PATH}"
      - "${PWD}/genesis_l2.json:${JWT_SECRET_PATH}"
    environment:
      - GETH_DATA_DIR=/db
      - GENESIS_FILE_PATH=/genesis.json
      - JWT_SECRET_PATH=/jwt-secret.txt
    entrypoint: # pass the L2 specific flags by overriding the entry-point and adding extra arguments
      - "/bin/sh"
      - "/entrypoint.sh"
